name: test addition operation

on:
  push:
    branches: 
      - master
  pull-request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: composer install
        uses: php-actions/composer@v6 # or alternative dependency management

      - name: phpunit install
        uses: php-actions/phpunit@v3
        with:
          php_extensions: "xdebug"
          coverage_clover: "coverage/clover.xml"

      - run: vendor/bin/phpunit

