name: test addition operation

on:
  push:
    branches: 
      - master
  pull-request:
    branches: 
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'  

      - name: Install dependencies
        run: composer install

      - name: Run tests
        run: ./vendor/bin/phpunit --verbose

